# Generated by Django 6.0.1 on 2026-01-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My baby', max_length=50)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter birth weight in kg', max_digits=4, null=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter birth height in cm', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g., hair and eye color, character', max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('breast', 'Breast'), ('bottle', 'Bottle'), ('solid', 'Solid')], max_length=10)),
                ('amount', models.FloatField(help_text='Amount in ml or grams')),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_tracker_app.baby')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Enter weight in kg', max_digits=4, null=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='Enter height in cm', max_digits=5, null=True)),
                ('milestone_note', models.TextField(blank=True, help_text='e.g., First Smile, Crawling, New word', max_length=200)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_tracker_app.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_tracker_app.baby')),
            ],
        ),
    ]
