# Generated by Django 6.0.1 on 2026-01-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='feed_type',
            field=models.IntegerField(choices=[(1, 'Breast'), (2, 'Bottle'), (3, 'Solid')], default=1),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
