# Generated by Django 6.0.1 on 2026-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0002_alter_feeding_feed_type_alter_feeding_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowthMilestones',
            new_name='Growth',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='feeding',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='growth',
            old_name='milestone_note',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Breast'), (2, 'Bottle'), (3, 'Solid')], default=1),
        ),
    ]
