# Generated by Django 6.0.1 on 2026-01-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0003_rename_growthmilestones_growth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='height',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='weight',
        ),
    ]
