# Generated by Django 6.0.1 on 2026-01-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0004_remove_baby_birth_date_remove_baby_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
