# Generated by Django 6.0.1 on 2026-01-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0005_baby_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='slug',
        ),
    ]
