# Generated by Django 6.0.1 on 2026-02-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0006_remove_baby_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='baby_tracker_app_images/'),
        ),
    ]
