# Generated by Django 6.0.1 on 2026-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0007_baby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Boy'), ('F', 'Girl')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='note',
            field=models.TextField(blank=True, help_text='e.g., hair and eye color, character', max_length=100),
        ),
    ]
