# Generated by Django 6.0.1 on 2026-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_tracker_app', '0008_baby_birth_date_baby_gender_alter_baby_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='milk_type',
            field=models.CharField(blank=True, choices=[('formula', 'Formula'), ('breast_milk', 'Breast Milk')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='amount',
            field=models.FloatField(blank=True, help_text='Amount in ml or grams', null=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Left Breast'), (2, 'Right Breast'), (3, 'Bottle'), (4, 'Solid')]),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
